### ISSUE TITLE
Adding extra logging for data

### ISSUE THREAD

**Issue by Wensink** [magneticio/vamp-node-client#12]
In the http.js logging is currently there for the HTTP REQUEST and RESPONSE.
The logging of the data passed is still missing. Can this be added as well?

        if (data) {
          logger.log('HTTP DATA [' + localIndex + '] ' + data);
          req.write(data);
        }

**Comment by dragoslav** [comment]
I don't see any problem, you can even make a PR if you want.
Later https://github.com/magneticio/vamp-workflow-agent/blob/573919935dd4fe81360f1666b09620c9c8cf3c07/package.json#L15 needs to be updated as well.

**Comment by dragoslav** [comment]
Thanks @Wensink PR is merged to master. I will update the commit hash.

**Comment by dragoslav** [comment]
`ci-174` and later contain this change.
